#!/bin/bash
export ENV_DATABASE_PORT="3306"
export ENV_DATABASE_ROOT_PASSWORD="root"
export ENV_DATABASE_DATABASE="testdb"
export ENV_DATABASE_APPLICATION_USER="user"
export ENV_DATABASE_APPLICATION_PASSWORD="password"
